<script setup>
import ModalFooter from "@/Components/Modals/Components/ModalFooter.vue";
import ModalBody from "@/Components/Modals/Components/ModalBody.vue";
import Modal from "@/Components/Modals/Modal.vue";
import ModalHeader from "@/Components/Modals/Components/ModalHeader.vue";
import { storeToRefs } from 'pinia';
import { useModalStore } from "@/store/modal.js";
import InputError from "@/Components/InputError.vue";
import InputLabel from "@/Components/InputLabel.vue";
import NumberInput from "@/Components/NumberInput.vue";
import InputHelper from "@/Components/InputHelper.vue";
import DropDownWithCheckbox from "@/Components/Form/DropDownWithCheckbox.vue";
import DropDownWithRadio from "@/Components/Form/DropDownWithRadio.vue";
import TextInputBlock from "@/Components/Form/TextInputBlock.vue";
import Dropzone from "@/Components/Form/Dropzone.vue";
import UserFormSection from "@/Modals/User/Partials/UserFormSection.vue";
import { computed, ref, watch } from "vue";
import { router } from '@inertiajs/vue3';
import { isRemovedDetailType, stripRemovedDetailTypes } from "@/utils/paymentDetail.js";
import { generatePaymentGatewayCode } from "@/utils/paymentGatewayCode.js";

const filterDetailTypeOptions = (items) => (items || []).filter((item) => !isRemovedDetailType(item.code));

const modalStore = useModalStore();
const { paymentGatewayCreateModal, paymentGatewayEditModal } = storeToRefs(modalStore);

const loading = ref(false);
const processing = ref(false);
const errors = ref({});

const currencies = ref([]);
const detail_types = ref([]);
const primeTimeCommissionRate = ref(0);

const paymentGateway = ref(null);
const codeManuallyEdited = ref(false);
const lastAutoGeneratedCode = ref('');

const isEditMode = computed(() => paymentGatewayEditModal.value.showed);
const isCreateMode = computed(() => paymentGatewayCreateModal.value.showed && !paymentGatewayEditModal.value.showed);
const isModalShown = computed(() => paymentGatewayCreateModal.value.showed || paymentGatewayEditModal.value.showed);
const canShowForm = computed(() => !isEditMode.value || !!paymentGateway.value);
const modalTitle = computed(() => {
    if (isEditMode.value) {
        return paymentGateway.value
            ? `Редактирование платежного метода - ${paymentGateway.value.name}`
            : 'Редактирование платежного метода';
    }
    return 'Создание платежного метода';
});

const makeTier = (from = null, to = null, rate = null) => ({
    from,
    to,
    rate,
});

const splitPoint = ref(null);

const normalizeTiers = (tiers) => {
    if (!Array.isArray(tiers)) {
        return [];
    }

    return tiers.map((tier) => makeTier(
        tier?.from ?? null,
        tier?.to ?? null,
        tier?.rate ?? null
    ));
};

const toNumberOrNull = (value) => {
    const number = Number(value);
    return Number.isFinite(number) ? number : null;
};

const getLimits = () => {
    const min = toNumberOrNull(form.value.min_limit);
    const max = toNumberOrNull(form.value.max_limit);

    if (min === null || max === null || min >= max) {
        return null;
    }

    return { min, max };
};

const clearTiersGeneralError = (field = 'trader_commission_tiers_for_orders') => {
    if (!errors.value?.[field]) {
        return;
    }

    const next = { ...errors.value };
    delete next[field];
    errors.value = next;
};

const setTiersGeneralError = (message, field = 'trader_commission_tiers_for_orders') => {
    errors.value = {
        ...errors.value,
        [field]: [message],
    };
};

const buildContiguousTiers = (innerPoints, sourceTiers = [], fallbackRate = 0) => {
    const limits = getLimits();
    if (!limits) {
        return [];
    }

    const points = Array.from(new Set(
        innerPoints
            .map((point) => toNumberOrNull(point))
            .filter((point) => point !== null && point > limits.min && point < limits.max)
    )).sort((left, right) => left - right);

    const boundaries = [limits.min, ...points, limits.max];
    const safeFallbackRate = toNumberOrNull(fallbackRate) ?? 0;

    return boundaries.slice(0, -1).map((from, index) => {
        const to = boundaries[index + 1];
        const midpoint = from + (to - from) / 2;
        const sourceTier = sourceTiers.find((tier, tierIndex) => {
            const tierFrom = toNumberOrNull(tier?.from);
            const tierTo = toNumberOrNull(tier?.to);
            if (tierFrom === null || tierTo === null) {
                return false;
            }

            const isLast = tierIndex === sourceTiers.length - 1;
            return isLast ? (midpoint >= tierFrom && midpoint <= tierTo) : (midpoint >= tierFrom && midpoint < tierTo);
        });

        return makeTier(
            from,
            to,
            toNumberOrNull(sourceTier?.rate) ?? safeFallbackRate
        );
    });
};

const alignTiersWithLimits = (tierField, fallbackRateField) => {
    const limits = getLimits();
    if (!limits) {
        form.value[tierField] = [];
        return;
    }

    const source = normalizeTiers(form.value[tierField]);
    const innerPoints = source
        .slice(0, -1)
        .map((tier) => toNumberOrNull(tier.to))
        .filter((point) => point !== null);

    form.value[tierField] = buildContiguousTiers(innerPoints, source, form.value[fallbackRateField]);
};

const syncTotalServiceTiersWithTraderBoundaries = () => {
    const traderTiers = normalizeTiers(form.value.trader_commission_tiers_for_orders);
    const innerPoints = traderTiers
        .slice(0, -1)
        .map((tier) => toNumberOrNull(tier.to))
        .filter((point) => point !== null);

    form.value.total_service_commission_tiers_for_orders = buildContiguousTiers(
        innerPoints,
        normalizeTiers(form.value.total_service_commission_tiers_for_orders),
        form.value.total_service_commission_rate_for_orders
    );
};

const alignAllFlexibleTiersWithLimits = () => {
    alignTiersWithLimits('trader_commission_tiers_for_orders', 'trader_commission_rate_for_orders');
    syncTotalServiceTiersWithTraderBoundaries();
};

const form = ref({
    name: null,
    code: null,
    min_limit: null,
    max_limit: null,
    trader_commission_rate_for_orders: 7,
    total_service_commission_rate_for_orders: 10,
    trader_commission_rate_for_payouts: 2,
    total_service_commission_rate_for_payouts: 3,
    is_active: true,
    is_intrabank: false,
    reservation_time_for_orders: null,
    reservation_time_for_payouts: null,
    currency: 'RUB',
    detail_types: [],
    logo: null,
    use_flexible_trader_commission_for_orders: false,
    trader_commission_tiers_for_orders: [],
    total_service_commission_tiers_for_orders: [],
});

const resetCommonState = () => {
    splitPoint.value = null;
    errors.value = {};
    paymentGateway.value = null;
};

const resetFormForCreate = () => {
    codeManuallyEdited.value = false;
    lastAutoGeneratedCode.value = '';
    form.value = {
        name: null,
        code: null,
        min_limit: null,
        max_limit: null,
        trader_commission_rate_for_orders: 7,
        total_service_commission_rate_for_orders: 10,
        trader_commission_rate_for_payouts: 7,
        total_service_commission_rate_for_payouts: 10,
        is_active: true,
        is_intrabank: false,
        reservation_time_for_orders: 10,
        reservation_time_for_payouts: 10,
        currency: 'RUB',
        detail_types: [],
        logo: null,
        use_flexible_trader_commission_for_orders: false,
        trader_commission_tiers_for_orders: [],
        total_service_commission_tiers_for_orders: [],
    };
    resetCommonState();
};

const resetFormForEdit = () => {
    form.value = {
        name: null,
        code: null,
        min_limit: null,
        max_limit: null,
        trader_commission_rate_for_orders: null,
        total_service_commission_rate_for_orders: null,
        trader_commission_rate_for_payouts: null,
        total_service_commission_rate_for_payouts: null,
        is_active: true,
        is_intrabank: false,
        reservation_time_for_orders: null,
        reservation_time_for_payouts: null,
        currency: 'RUB',
        detail_types: [],
        logo: null,
        use_flexible_trader_commission_for_orders: false,
        trader_commission_tiers_for_orders: [],
        total_service_commission_tiers_for_orders: [],
    };
    resetCommonState();
};

const close = () => {
    modalStore.closeModal('paymentGatewayCreate');
    modalStore.closeModal('paymentGatewayEdit');
};

const loadCreateData = () => {
    loading.value = true;
    axios.get(route('admin.payment-gateways.create-data'))
        .then(response => {
            const data = response.data?.data || response.data || {};
            currencies.value = data.currencies || [];
            detail_types.value = filterDetailTypeOptions(data.detailTypes || []);
            primeTimeCommissionRate.value = data.primeTimeCommissionRate || 0;
            loading.value = false;
        })
        .catch(() => {
            loading.value = false;
        });
};

const loadEditData = () => {
    if (!paymentGatewayEditModal.value.params?.paymentGatewayId) return;
    loading.value = true;
    axios.get(route('admin.payment-gateways.edit-data', paymentGatewayEditModal.value.params.paymentGatewayId))
        .then(response => {
            const data = response.data?.data || response.data || {};
            currencies.value = data.currencies || [];
            detail_types.value = filterDetailTypeOptions(data.detailTypes || []);
            paymentGateway.value = data.paymentGateway;
            form.value.name = paymentGateway.value.original_name;
            form.value.code = paymentGateway.value.code;
            form.value.min_limit = paymentGateway.value.min_limit;
            form.value.max_limit = paymentGateway.value.max_limit;
            form.value.trader_commission_rate_for_orders = paymentGateway.value.trader_commission_rate_for_orders;
            form.value.total_service_commission_rate_for_orders = paymentGateway.value.total_service_commission_rate_for_orders;
            form.value.is_active = !!paymentGateway.value.is_active;
            form.value.is_intrabank = !!paymentGateway.value.is_intrabank;
            form.value.reservation_time_for_orders = paymentGateway.value.reservation_time_for_orders;
            form.value.trader_commission_rate_for_payouts = paymentGateway.value.trader_commission_rate_for_payouts;
            form.value.total_service_commission_rate_for_payouts = paymentGateway.value.total_service_commission_rate_for_payouts;
            form.value.reservation_time_for_payouts = paymentGateway.value.reservation_time_for_payouts;
            form.value.use_flexible_trader_commission_for_orders = !!paymentGateway.value.use_flexible_trader_commission_for_orders;
            form.value.trader_commission_tiers_for_orders = normalizeTiers(paymentGateway.value.trader_commission_tiers_for_orders);
            form.value.total_service_commission_tiers_for_orders = normalizeTiers(paymentGateway.value.total_service_commission_tiers_for_orders);
            if (form.value.use_flexible_trader_commission_for_orders) {
                alignAllFlexibleTiersWithLimits();
            }
            form.value.currency = (paymentGateway.value.currency || 'RUB').toUpperCase();
            form.value.detail_types = stripRemovedDetailTypes(paymentGateway.value.detail_types ?? []);
            loading.value = false;
        })
        .catch(() => {
            loading.value = false;
        });
};

const fillSingleTierByLimits = () => {
    const limits = getLimits();
    if (!limits) {
        setTiersGeneralError('Сначала укажите корректные min_limit и max_limit.');
        return;
    }

    clearTiersGeneralError();
    form.value.trader_commission_tiers_for_orders = [makeTier(
        limits.min,
        limits.max,
        toNumberOrNull(form.value.trader_commission_rate_for_orders) ?? 0
    )];
    form.value.total_service_commission_tiers_for_orders = [makeTier(
        limits.min,
        limits.max,
        toNumberOrNull(form.value.total_service_commission_rate_for_orders) ?? 0
    )];
};

const splitTierAtPoint = () => {
    const limits = getLimits();
    if (!limits) {
        setTiersGeneralError('Сначала укажите корректные min_limit и max_limit.');
        return;
    }

    alignAllFlexibleTiersWithLimits();
    const tiers = form.value.trader_commission_tiers_for_orders;
    if (!tiers.length) {
        fillSingleTierByLimits();
    }

    const point = toNumberOrNull(splitPoint.value);
    if (point === null || point <= limits.min || point >= limits.max) {
        setTiersGeneralError(`Граница должна быть строго между ${limits.min} и ${limits.max}.`);
        return;
    }

    const splitIndex = tiers.findIndex((tier) => point > tier.from && point < tier.to);
    if (splitIndex === -1) {
        setTiersGeneralError('Эта граница уже существует или выходит за текущие уровни.');
        return;
    }

    const targetTier = tiers[splitIndex];
    const leftTier = makeTier(targetTier.from, point, targetTier.rate);
    const rightTier = makeTier(point, targetTier.to, targetTier.rate);
    tiers.splice(splitIndex, 1, leftTier, rightTier);

    const innerPoints = tiers.slice(0, -1).map((tier) => toNumberOrNull(tier.to)).filter((point) => point !== null);
    form.value.total_service_commission_tiers_for_orders = buildContiguousTiers(
        innerPoints,
        normalizeTiers(form.value.total_service_commission_tiers_for_orders),
        form.value.total_service_commission_rate_for_orders
    );

    splitPoint.value = null;
    clearTiersGeneralError();
};

const removeCommissionTier = (index) => {
    const tiers = form.value.trader_commission_tiers_for_orders;
    if (tiers.length <= 1) {
        return;
    }

    if (index === 0) {
        tiers[1].from = tiers[0].from;
    } else {
        tiers[index - 1].to = tiers[index].to;
    }

    form.value.trader_commission_tiers_for_orders = tiers.filter((_, i) => i !== index);
    const nextInnerPoints = form.value.trader_commission_tiers_for_orders
        .slice(0, -1)
        .map((tier) => toNumberOrNull(tier.to))
        .filter((point) => point !== null);
    form.value.total_service_commission_tiers_for_orders = buildContiguousTiers(
        nextInnerPoints,
        normalizeTiers(form.value.total_service_commission_tiers_for_orders),
        form.value.total_service_commission_rate_for_orders
    );
    clearTiersGeneralError();
};

watch(
    () => form.value.name,
    (name) => {
        if (!isCreateMode.value || codeManuallyEdited.value) {
            return;
        }

        const generatedCode = generatePaymentGatewayCode(name);
        lastAutoGeneratedCode.value = generatedCode;
        form.value.code = generatedCode;
    }
);

watch(
    () => form.value.code,
    (code) => {
        if (!isCreateMode.value || codeManuallyEdited.value) {
            return;
        }

        if ((code ?? '') !== lastAutoGeneratedCode.value) {
            codeManuallyEdited.value = true;
        }
    }
);

watch(() => form.value.is_intrabank, (newValue) => {
    if (newValue) {
        form.value.detail_types = form.value.detail_types.filter(type => !['phone', 'mobile_commerce'].includes(type));
    }
});

watch(
    () => form.value.use_flexible_trader_commission_for_orders,
    (enabled) => {
        if (!enabled) {
            return;
        }

        if (!Array.isArray(form.value.trader_commission_tiers_for_orders) || !form.value.trader_commission_tiers_for_orders.length) {
            fillSingleTierByLimits();
            return;
        }

        alignAllFlexibleTiersWithLimits();
    }
);

watch(
    () => [form.value.min_limit, form.value.max_limit],
    () => {
        if (!form.value.use_flexible_trader_commission_for_orders) {
            return;
        }

        alignAllFlexibleTiersWithLimits();
    }
);

const toFormData = (is_edit) => {
    const fd = new FormData();
    fd.append('name', form.value.name ?? '');
    fd.append('code', form.value.code ?? '');
    fd.append('min_limit', form.value.min_limit ?? '');
    fd.append('max_limit', form.value.max_limit ?? '');
    fd.append('trader_commission_rate_for_orders', form.value.trader_commission_rate_for_orders ?? '');
    fd.append('use_flexible_trader_commission_for_orders', form.value.use_flexible_trader_commission_for_orders ? '1' : '0');
    if (form.value.use_flexible_trader_commission_for_orders) {
        alignAllFlexibleTiersWithLimits();
        (form.value.trader_commission_tiers_for_orders || []).forEach((tier, index) => {
            fd.append(`trader_commission_tiers_for_orders[${index}][from]`, tier.from ?? '');
            fd.append(`trader_commission_tiers_for_orders[${index}][to]`, tier.to ?? '');
            fd.append(`trader_commission_tiers_for_orders[${index}][rate]`, tier.rate ?? '');
        });
        (form.value.total_service_commission_tiers_for_orders || []).forEach((tier, index) => {
            fd.append(`total_service_commission_tiers_for_orders[${index}][from]`, tier.from ?? '');
            fd.append(`total_service_commission_tiers_for_orders[${index}][to]`, tier.to ?? '');
            fd.append(`total_service_commission_tiers_for_orders[${index}][rate]`, tier.rate ?? '');
        });
    }
    fd.append('total_service_commission_rate_for_orders', form.value.total_service_commission_rate_for_orders ?? '');
    fd.append('trader_commission_rate_for_payouts', form.value.trader_commission_rate_for_payouts ?? '');
    fd.append('total_service_commission_rate_for_payouts', form.value.total_service_commission_rate_for_payouts ?? '');
    fd.append('is_active', form.value.is_active ? '1' : '0');
    fd.append('is_intrabank', form.value.is_intrabank ? '1' : '0');
    fd.append('reservation_time_for_orders', form.value.reservation_time_for_orders ?? '');
    fd.append('reservation_time_for_payouts', form.value.reservation_time_for_payouts ?? '');
    fd.append('currency', (form.value.currency || 'RUB').toString().toUpperCase());
    stripRemovedDetailTypes(form.value.detail_types || []).forEach(v => fd.append('detail_types[]', v));
    if (form.value.logo) {
        fd.append('logo', form.value.logo);
    }
    if (is_edit) {
        fd.append('_method', 'PATCH');
    }
    return fd;
};

const submitCreate = () => {
    processing.value = true;
    errors.value = {};
    axios.post(route('admin.payment-gateways.store'), toFormData(false), {
        headers: { 'Accept': 'application/json' }
    })
        .then(response => {
            processing.value = false;
            if (response.data?.success || response.status === 200 || response.status === 201) {
                close();
                resetFormForCreate();
                router.reload({ only: ['paymentGateways'] });
            }
        })
        .catch(error => {
            processing.value = false;
            if (error.response && error.response.data && error.response.data.errors) {
                errors.value = error.response.data.errors;
            }
        });
};

const submitEdit = () => {
    if (!paymentGateway.value) return;
    processing.value = true;
    errors.value = {};
    axios.post(route('admin.payment-gateways.update', paymentGateway.value.id), toFormData(true), {
        headers: { 'Accept': 'application/json' }
    })
        .then(response => {
            processing.value = false;
            if (response.data?.success || response.status === 200 || response.status === 204) {
                close();
                resetFormForEdit();
                router.reload({ only: ['paymentGateways'] });
            }
        })
        .catch(error => {
            processing.value = false;
            if (error.response && error.response.data) {
                if (error.response.data.errors) {
                    errors.value = error.response.data.errors;
                } else if (error.response.data.message) {
                    errors.value = { name: [error.response.data.message] };
                }
            }
        });
};

const submit = () => {
    if (isEditMode.value) {
        submitEdit();
        return;
    }
    submitCreate();
};

watch(
    () => isCreateMode.value,
    (state) => {
        if (state) {
            resetFormForCreate();
            loadCreateData();
        } else if (!isEditMode.value) {
            resetFormForCreate();
        }
    }
);

watch(
    () => isEditMode.value,
    (state) => {
        if (state) {
            resetFormForEdit();
            loadEditData();
        } else if (!isCreateMode.value) {
            resetFormForEdit();
        }
    }
);
</script>

<template>
    <Modal :show="isModalShown" @close="close" maxWidth="4xl">
        <ModalHeader @close="close" :title="modalTitle" />

        <ModalBody>
            <div v-if="loading" class="py-4 text-center">
                <span class="loading loading-spinner loading-md"></span>
            </div>
            <div v-else>
                <form v-if="canShowForm" @submit.prevent="submit" class="space-y-4">
                    <UserFormSection title="Основное" compact>
                        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                            <TextInputBlock
                                v-model="form.name"
                                :form="{ errors: errors }"
                                field="name"
                                label="Название"
                                placeholder="Сбербанк"
                            />

                            <TextInputBlock
                                v-model="form.code"
                                :form="{ errors: errors }"
                                field="code"
                                label="Код метода"
                                placeholder="sberbank"
                                :helper="isCreateMode ? 'Заполняется автоматически из названия. Можно изменить вручную.' : null"
                            />

                            <div>
                                <DropDownWithCheckbox
                                    v-model="form.detail_types"
                                    :items="detail_types.filter(type => !form.is_intrabank || !['phone', 'mobile_commerce'].includes(type.code))"
                                    value="code"
                                    name="name"
                                    label="Тип реквизитов"
                                />
                                <InputError :message="errors.detail_types?.[0]" class="mt-1" />
                                <InputHelper v-if="form.is_intrabank" model-value="Типы «СБП» и «Моб. коммерция» недоступны для внутрибанковского перевода" />
                            </div>

                            <div>
                                <DropDownWithRadio
                                    v-model="form.currency"
                                    :items="currencies"
                                    value="code"
                                    name="code"
                                    label="Валюта"
                                />
                                <InputError :message="errors.currency?.[0]" class="mt-1" />
                            </div>
                        </div>
                    </UserFormSection>

                    <UserFormSection
                        title="Лимиты и время"
                        description="Лимит на сумму одной сделки. Время резервирования — в минутах."
                        compact
                    >
                        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
                            <div>
                                <InputLabel
                                    for="min_limit"
                                    :value="'Мин. сумма, ' + (form.currency || 'RUB')?.toUpperCase()"
                                    :error="!!errors.min_limit?.[0]"
                                />
                                <NumberInput
                                    id="min_limit"
                                    v-model="form.min_limit"
                                    class="mt-1 block w-full"
                                    placeholder="0"
                                    :error="!!errors.min_limit?.[0]"
                                    @input="errors.min_limit = null"
                                />
                                <InputError :message="errors.min_limit?.[0]" class="mt-1" />
                            </div>

                            <div>
                                <InputLabel
                                    for="max_limit"
                                    :value="'Макс. сумма, ' + (form.currency || 'RUB')?.toUpperCase()"
                                    :error="!!errors.max_limit?.[0]"
                                />
                                <NumberInput
                                    id="max_limit"
                                    v-model="form.max_limit"
                                    class="mt-1 block w-full"
                                    placeholder="0"
                                    :error="!!errors.max_limit?.[0]"
                                    @input="errors.max_limit = null"
                                />
                                <InputError :message="errors.max_limit?.[0]" class="mt-1" />
                            </div>

                            <div>
                                <InputLabel
                                    for="reservation_time_for_orders"
                                    value="Время на сделку"
                                    :error="!!errors.reservation_time_for_orders?.[0]"
                                />
                                <NumberInput
                                    id="reservation_time_for_orders"
                                    v-model="form.reservation_time_for_orders"
                                    class="mt-1 block w-full"
                                    placeholder="0"
                                    :error="!!errors.reservation_time_for_orders?.[0]"
                                    @input="errors.reservation_time_for_orders = null"
                                />
                                <InputError :message="errors.reservation_time_for_orders?.[0]" class="mt-1" />
                            </div>

                            <div>
                                <InputLabel
                                    for="reservation_time_for_payouts"
                                    value="Время на выплату"
                                    :error="!!errors.reservation_time_for_payouts?.[0]"
                                />
                                <NumberInput
                                    id="reservation_time_for_payouts"
                                    v-model="form.reservation_time_for_payouts"
                                    class="mt-1 block w-full"
                                    placeholder="0"
                                    :error="!!errors.reservation_time_for_payouts?.[0]"
                                    @input="errors.reservation_time_for_payouts = null"
                                />
                                <InputError :message="errors.reservation_time_for_payouts?.[0]" class="mt-1" />
                            </div>
                        </div>
                    </UserFormSection>

                    <UserFormSection title="Комиссии" compact>
                        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
                            <div>
                                <InputLabel
                                    for="trader_commission_rate_for_orders"
                                    value="Трейдер % (сделки)"
                                    :error="!!errors.trader_commission_rate_for_orders?.[0]"
                                />
                                <NumberInput
                                    id="trader_commission_rate_for_orders"
                                    v-model="form.trader_commission_rate_for_orders"
                                    class="mt-1 block w-full"
                                    step="0.1"
                                    placeholder="0.0"
                                    :error="!!errors.trader_commission_rate_for_orders?.[0]"
                                    @input="errors.trader_commission_rate_for_orders = null"
                                />
                                <InputError :message="errors.trader_commission_rate_for_orders?.[0]" class="mt-1" />
                                <InputHelper
                                    v-if="isCreateMode && !errors.trader_commission_rate_for_orders"
                                    model-value="Не больше комиссии сервиса. Учитывайте прайм-тайм."
                                />
                            </div>

                            <div>
                                <InputLabel
                                    for="total_service_commission_rate_for_orders"
                                    value="Тотал % (сделки)"
                                    :error="!!errors.total_service_commission_rate_for_orders?.[0]"
                                />
                                <NumberInput
                                    id="total_service_commission_rate_for_orders"
                                    v-model="form.total_service_commission_rate_for_orders"
                                    class="mt-1 block w-full"
                                    step="0.1"
                                    placeholder="0.0"
                                    :error="!!errors.total_service_commission_rate_for_orders?.[0]"
                                    @input="errors.total_service_commission_rate_for_orders = null"
                                />
                                <InputError :message="errors.total_service_commission_rate_for_orders?.[0]" class="mt-1" />
                            </div>

                            <div>
                                <InputLabel
                                    for="trader_commission_rate_for_payouts"
                                    value="Трейдер % (выплаты)"
                                    :error="!!errors.trader_commission_rate_for_payouts?.[0]"
                                />
                                <NumberInput
                                    id="trader_commission_rate_for_payouts"
                                    v-model="form.trader_commission_rate_for_payouts"
                                    class="mt-1 block w-full"
                                    step="0.1"
                                    placeholder="0.0"
                                    :error="!!errors.trader_commission_rate_for_payouts?.[0]"
                                    @input="errors.trader_commission_rate_for_payouts = null"
                                />
                                <InputError :message="errors.trader_commission_rate_for_payouts?.[0]" class="mt-1" />
                            </div>

                            <div>
                                <InputLabel
                                    for="total_service_commission_rate_for_payouts"
                                    value="Тотал % (выплаты)"
                                    :error="!!errors.total_service_commission_rate_for_payouts?.[0]"
                                />
                                <NumberInput
                                    id="total_service_commission_rate_for_payouts"
                                    v-model="form.total_service_commission_rate_for_payouts"
                                    class="mt-1 block w-full"
                                    step="0.1"
                                    placeholder="0.0"
                                    :error="!!errors.total_service_commission_rate_for_payouts?.[0]"
                                    @input="errors.total_service_commission_rate_for_payouts = null"
                                />
                                <InputError :message="errors.total_service_commission_rate_for_payouts?.[0]" class="mt-1" />
                            </div>
                        </div>

                        <div class="mt-3 rounded-box border border-base-300 bg-base-200/30 p-3">
                            <label class="label cursor-pointer justify-start gap-2 py-1">
                                <input
                                    type="checkbox"
                                    class="toggle toggle-primary toggle-sm"
                                    v-model="form.use_flexible_trader_commission_for_orders"
                                >
                                <span class="label-text text-sm">Гибкая комиссия по сумме сделки</span>
                            </label>
                            <InputError :message="errors.use_flexible_trader_commission_for_orders?.[0]" />

                            <div v-if="form.use_flexible_trader_commission_for_orders" class="mt-2 space-y-2">
                                <div class="flex flex-wrap items-end gap-2">
                                    <div class="min-w-0 flex-1 sm:max-w-xs">
                                        <InputLabel value="Граница диапазона" />
                                        <NumberInput v-model="splitPoint" placeholder="2000" />
                                    </div>
                                    <div class="join">
                                        <button type="button" class="btn btn-xs join-item btn-outline" @click="splitTierAtPoint">
                                            Разделить
                                        </button>
                                        <button type="button" class="btn btn-xs join-item" @click="fillSingleTierByLimits">
                                            1 уровень
                                        </button>
                                    </div>
                                </div>

                                <div
                                    v-for="(tier, index) in form.trader_commission_tiers_for_orders"
                                    :key="`tier-${index}`"
                                    class="rounded-lg border border-base-300/60 bg-base-100 p-2"
                                >
                                    <div class="mb-1.5 text-xs font-medium text-base-content/60">
                                        Уровень #{{ index + 1 }}
                                    </div>
                                    <div class="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-5">
                                        <div>
                                            <InputLabel value="От" />
                                            <div class="input input-bordered w-full">{{ tier.from }}</div>
                                            <InputError :message="errors[`trader_commission_tiers_for_orders.${index}.from`]?.[0]" class="mt-0.5" />
                                        </div>
                                        <div>
                                            <InputLabel value="До" />
                                            <div class="input input-bordered w-full">{{ tier.to }}</div>
                                            <InputError :message="errors[`trader_commission_tiers_for_orders.${index}.to`]?.[0]" class="mt-0.5" />
                                        </div>
                                        <div>
                                            <InputLabel value="Трейдер %" />
                                            <NumberInput v-model="tier.rate" step="0.1" placeholder="7" />
                                            <InputError :message="errors[`trader_commission_tiers_for_orders.${index}.rate`]?.[0]" class="mt-0.5" />
                                        </div>
                                        <div>
                                            <InputLabel value="Тотал %" />
                                            <NumberInput v-model="form.total_service_commission_tiers_for_orders[index].rate" step="0.1" placeholder="10" />
                                            <InputError :message="errors[`total_service_commission_tiers_for_orders.${index}.rate`]?.[0]" class="mt-0.5" />
                                        </div>
                                        <div class="col-span-2 flex items-end justify-end sm:col-span-4 xl:col-span-1">
                                            <button
                                                type="button"
                                                class="btn btn-xs btn-error btn-outline"
                                                @click="removeCommissionTier(index)"
                                                :disabled="form.trader_commission_tiers_for_orders.length <= 1"
                                            >
                                                Удалить
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <InputError :message="errors.trader_commission_tiers_for_orders?.[0]" />
                                <InputError :message="errors.total_service_commission_tiers_for_orders?.[0]" />
                                <InputHelper model-value="Диапазоны трейдера и сервиса должны идти подряд от min_limit до max_limit без разрывов." />
                            </div>
                        </div>
                    </UserFormSection>

                    <UserFormSection title="Логотип" compact>
                        <Dropzone
                            v-model="form.logo"
                            title="Нажмите, чтобы загрузить изображение"
                            description="PNG (квадрат 1×1)"
                        />
                        <InputError :message="errors.logo?.[0]" class="mt-1" />
                        <div v-if="isEditMode && paymentGateway && paymentGateway.logo_path" class="mt-2 flex items-center gap-2">
                            <img :src="paymentGateway.logo_path" class="size-14 rounded-lg border border-base-300 object-cover" alt="">
                            <span class="text-xs text-base-content/60">Текущий логотип</span>
                        </div>
                    </UserFormSection>

                    <UserFormSection title="Доступность" compact>
                        <div class="flex flex-col gap-1 sm:max-w-md">
                            <label
                                class="label cursor-pointer justify-start gap-2 rounded-lg border border-base-300 px-3 py-2"
                                :class="{ 'opacity-75': isEditMode && paymentGateway && paymentGateway.is_intrabank }"
                            >
                                <input
                                    type="checkbox"
                                    class="toggle toggle-primary toggle-sm"
                                    v-model="form.is_intrabank"
                                    :disabled="isEditMode && paymentGateway && paymentGateway.is_intrabank"
                                >
                                <span class="label-text text-sm">Внутрибанковский перевод</span>
                            </label>
                            <p v-if="isEditMode && paymentGateway && paymentGateway.is_intrabank" class="px-3 text-xs text-error">
                                Нельзя отключить после активации
                            </p>

                            <label class="label cursor-pointer justify-start gap-2 rounded-lg border border-base-300 px-3 py-2">
                                <input type="checkbox" class="toggle toggle-primary toggle-sm" v-model="form.is_active">
                                <span class="label-text text-sm">Метод активен</span>
                            </label>
                        </div>
                    </UserFormSection>
                </form>
            </div>
        </ModalBody>

        <ModalFooter>
            <button @click="close" type="button" class="btn btn-sm">
                Отмена
            </button>
            <button @click="submit" type="button" class="btn btn-sm btn-primary" :class="{ 'btn-disabled': processing }" :disabled="processing">
                Сохранить
            </button>
        </ModalFooter>
    </Modal>
</template>
